### ISSUE TITLE
TableView doesn't handle Conditional, Container, or multiple widgets

### ISSUE THREAD

**Issue by bredelings** [frmdstryr/enamlx#19]
If I put a  Container inside a TableViewItem, then the resulting cell is empty and just displays a white background.

```
                    TableViewItem:
                        Container:
                            Label:
                                text << model.imodels[partition.substitution_model].name if not partition.fixed_alignment else 'none'
```
I tried putting two Label items inside the TableView, and in that case it displayed the second Label.

I trued putting two Conditionals inside the TableView, with opposite conditions, so that only only condition is true at a time, and it starts by displaying the first Conditional, but when I toggle the condition, I just get an empty cell:
```
                    TableViewItem:
                        Conditional:
                            condition << row >=0 and row < len(table.items) and not partition.fixed_alignment
                            Label:
                                text << model.imodels[partition.substitution_model].name if not partition.fixed_alignment else 'none'
                        Conditional:
                            condition << row >=0 and row < len(table.items) and partition.fixed_alignment
                            Label:
                                text << 'none'
                        double_clicked :: print("Double clicked %s"%partition.indel_model)
                        selected :: print("Selection %s is now %s"%(partition.indel_model,change['value']))
```
